### ISSUE TITLE
Unbootable Image

### ISSUE THREAD

**Issue by aaronjamt** [mrthefakeperson/16-Bit-Bootloader#1]
After compiling, I realized that it would not boot. I looked through your code, and found line 66 of boot_sect.asm, which says `dw 0xaa55`. That line should say `dw 0x55aa` or `dw 0x55AA` if the bootloader is supposed to boot.

**Comment by mrthefakeperson** [comment]
There might be some inconsistency in the endian-ness of different assemblers. I believe that the bios expects `0x55` `0xAA`, so replacing that line with the two lines `db 0x55` and `db 0xAA` should fix this.
